dependencies:
- name: bdd-test-create-spring-1533028819
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-python-http-1533028819
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-react-quickstart-1533028819
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-rust-http-1533028819
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
